apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: default
data:
  APP_ENV: "production-portfolio"
  # 🚀 AWS RE-TAG: Updates your system variables to reflect your real AWS data center
  CLUSTER_REGION: "aws-eks-us-east-1"
  REPLICA_COUNT: "2"

