apiVersion: v1
kind: Secret
metadata:
  name: postgres-db-secret
  namespace: default
type: Opaque
stringData:
  # Kubernetes will automatically convert stringData into base64 tokens
  POSTGRES_DB: dev_db
  POSTGRES_USER: db_admin
  POSTGRES_PASSWORD: SecureSuperPassword123!ppp

