apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  # 🚀 AWS LINK: Explicitly tells EKS to request an AWS EBS storage volume!
  storageClassName: gp2
  resources:
    requests:
      storage: 1Gi

