apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  # This activates the hidden Nginx logs so the exporter can read them!
  status.conf: |
    server {
        listen 80;
        server_name localhost;
        location /stub_status {
            stub_status on;
            access_log off;
            allow 127.0.0.1;
            deny all;
        }
    }

