name: Cloud-Native Portfolio CI/CD

on:
  push:
    branches: [ "dev-1", "main" ]

jobs:
  # --- GATEWAY 1: RUNS ON BOTH DEV-1 AND MAIN PUSHES ---
  validate-and-lint:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Lint Dockerfile syntax
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: Dockerfile
        failure-threshold: error

    - name: Validate Kubernetes YAML Syntax
      uses: stefanprodan/kube-tools@v1
      with:
        kubectl: 1.28.2
        command: |
          kubectl kubeval kubernetes/secret.yaml
          kubectl kubeval kubernetes/postgres-db.yaml
          kubectl kubeval kubernetes/frontend-app.yaml

  # --- GATEWAY 2: RUNS EXCLUSIVELY ON MAIN PUSHES/MERGES ---
  build-and-deploy:
    needs: validate-and-lint
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Log in to DockerHub Registry
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Production Nginx Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/multi-page-nginx:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/multi-page-nginx:${{ github.sha }}

